### PR TITLE
Dont require corrections for licensee

### PR DESCRIPTION
**Pull request by jayvdb**
User story: I would like to add licensee as a dev-dep, and run licensee without `--corrections`, and without having to manually add a license exception.

### CODE REVIEW

**Comment by kemitchell** [comment]
Could you further explain your rationale for this change?

If it's that `docopt` doesn't have license metadata set, you can also get 0 exit codes by adding a package-specific exception to your Licensee configuration file.

**Comment by jayvdb** [comment]
This tool should choose dependencies that are properly licensed, so that it isnt the cause of improperly licensed dependencies being added to users dependency tree.

**Comment by kemitchell** [comment]
Could you please be more specific?

If your concern is the `docopt` npm package, please have a look at the `LICENSE-MIT` file in its repository.

**Comment by jayvdb** [comment]
The concern is that docopt's published version lacks the licensing metadata needed by lots of software composition analysis (SCA) tools.

As licensee.js is a SCA tool, I expect it to have dependencies that are free of SCA problems.

As you have been a committer to docopt project, perhaps you can also help with resolving the problem there, which would be even better than solving it here. 
c.f. https://github.com/stuartcarnie/docopt.coffee/pull/14#issuecomment-2395611418

**Comment by kemitchell** [comment]
> As licensee.js is a SCA tool, I expect it to have dependencies that are free of SCA problems.

Neither I nor any other committer here owes you any time or attention. When asking for our help, I'd suggest you'll have more success asking politely and taking the time to thoroughly explain the changes you propose. Not making work here while you also [address the direct issue with `docopt`](https://github.com/stuartcarnie/docopt.coffee/pull/14#issuecomment-2395611418). Not by writing "I expect" when what you really mean is just "I want".

**Pull request closed without merging**
