### PR TITLE
Add gitignore and npmignore

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by kemitchell** [comment]
@brettz9 if you do Node/JavaScript development, I'd strongly recommend you put `user_modules` in user-global `.gitignore`.

This package probably _should_ exclude tests from distribution tarballs. Would you like to land that PR yourself, or should I go ahead and do it?

**Comment by brettz9** [comment]
Sorry, are you asking to just add `user_modules` (along with `node_modules`) in `.gitignore`?

I am behind the Great Firewall in China, and can't get around it atm, so not able to Google `user_modules`, but thanks for the tip.

**Comment by kemitchell** [comment]
I do:

```bash
echo >> ~/.gitconfig <<EOS
[core]
excludes_file = ~/.gitignore_global
EOS
echo node_modules >> ~/.gitignore_global
```

**Comment by ljharb** [comment]
I’m not familiar with user_modules; node_modules should be gitignored and i believe needn’t be npmignored since npm will always ignore it unless bundledDependencies are specified.

**Comment by kemitchell** [comment]
`user_modules` was a typo. Might've been my phone.

**Comment by brettz9** [comment]
@kemitchell : Re: global gitignore, while I understand the appeal, I think the advantage of a local one is consistency among project developers. Of the good many projects I've submitted PRs for, I've come across quite a few who have strong opinions about whether to include or exclude `package-lock.json` and such, but I don't think I've come across any others who expected a `.gitignore_global`. But if you don't want it, I can amend to only include the `.npmignore` in this PR.

**Comment by kemitchell** [comment]
@brettz9 I don't think we need an `.npmignore`. The `package.json` file for this package uses a `files` array. And indeed there aren't any test files in the latest tarball:

```bash
mkdir tmp
cd tmp
npm i -D licensee
ls node_modules/licensee
```

I hear you on `.gitignore`. The argument that got me years ago boils down to this: Should nearly npm package project have `node_modules` in `.gitignore`? If so, and I think so, then `node_modules` should be ignored by default, rather than cluttering every repository with the same `.gitignore`.

**Comment by brettz9** [comment]
Re: npmignore, yeah, sorry, I seem to have a mental block in forgetting to check `files`.

Re: gitignore, assuming Git, which is of course not Node specific and has no mechanism for detecting the language, would agree to such a default, it could still cause problems with those using `bundledDependencies` who actually include `node_modules` in their repositories.

**Comment by kemitchell** [comment]
`git add --force node_modules` overrides the default.

**Comment by brettz9** [comment]
So where is your proposal to Git to allow `node_modules` by default, so we can all benefit from this? :-)

**Comment by kemitchell** [comment]
It's a user-space thing.

https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore

https://github.com/github/gitignore/blob/master/Node.gitignore#L41

**Comment by brettz9** [comment]
I guess it is a reasonable practice and even if it causes me to forget adding it where explicit `.gitignore` files are needed, I can justify it, since it is really hardly project-specific for Node users. Thanks!

**Pull request closed without merging**
