### PR TITLE
Optionally apply npm-license-corrections (close #32) (close #35)

### LINKED ISSUE #32: Support third-party assessments of package license?
I've been thinking a bit about allowing `licensee` to use external "mappings" from `package@version` to SPDX ID, for those packages that have an SPDX-identified license, but haven't coded it correctly in `package.json`.

I find myself copying the same `whitelist` mappings from project to project. This could solve.

### LINKED ISSUE #35: Support Use of npm-license-corrections
1. When reading a dep, check if it's been corrected, and substitute the corrected `license` value.
2. Apply the `rule` and `whitelist` as usual.

### PR DESCRIPTION
**Pull request by kemitchell**
Waiting on a 1.0.0 release of npm-license-corrections.

### CODE REVIEW

**Comment by kemitchell** [comment]
@ljharb here we go...

**Comment by kemitchell** [comment]
> To add my own corrections (i have a manual list built up) i'd make a PR to the npm-license-corrections repo?

Yep. I could also use your eyes on the pull request template there: https://github.com/jslicense/npm-license-corrections.json/blob/master/.github/pull_request_template.md

**Comment by ljharb** [comment]
i mean, in most of my "corrections" cases, the license was explicitly MIT from the get-go, it's just that it didn't use the SPDX standard until a certain version - do i need to ask the author in that case?

**Comment by ljharb** [comment]
also, does it have to be one per version, or can i use a semver range like in the whitelist?

**Comment by kemitchell** [comment]
Issues on the list repo?

**Pull request merged**
